name: License checker

on:
  workflow_dispatch: {}
jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
    - uses: actions/checkout@v2
    - name: Check License Header
      uses: apache/skywalking-eyes/header@df70871af1a8109c9a5b1dc824faaf65246c5236
