name: "PR Title Checker"
on:
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: thehanimo/pr-title-checker@v1.3.4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pass_on_octokit_error: false
        configuration_path: ".github/pr-title-checker-config.json"
